# Generated by Django 4.2.2 on 2023-06-29 12:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='media/pic/png', upload_to=app.models.upload_path),
            preserve_default=False,
        ),
    ]
