# Generated by Django 4.2.2 on 2023-06-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
